# Generated by Django 3.1.7 on 2021-03-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='후보자이름')),
                ('poster', models.ImageField(blank=True, upload_to='profile_image/%Y/%m/%d', verbose_name='프로필 이미지')),
                ('url', models.URLField(blank=True, verbose_name='온라인공약집링크')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문')),
                ('background', models.TextField(verbose_name='질문에 대한 배경 설명')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=100, verbose_name='후보자이름')),
                ('q1', models.PositiveIntegerField(verbose_name='1번 질문의 답')),
                ('q2', models.PositiveIntegerField(verbose_name='2번 질문의 답')),
                ('q3', models.PositiveIntegerField(verbose_name='3번 질문의 답')),
                ('q4', models.PositiveIntegerField(verbose_name='4번 질문의 답')),
                ('q5', models.PositiveIntegerField(verbose_name='5번 질문의 답')),
                ('q6', models.PositiveIntegerField(verbose_name='6번 질문의 답')),
                ('q7', models.PositiveIntegerField(verbose_name='7번 질문의 답')),
                ('q8', models.PositiveIntegerField(verbose_name='8번 질문의 답')),
                ('q9', models.PositiveIntegerField(verbose_name='9번 질문의 답')),
                ('q10', models.PositiveIntegerField(verbose_name='10번 질문의 답')),
                ('q11', models.PositiveIntegerField(verbose_name='11번 질문의 답')),
                ('q12', models.PositiveIntegerField(verbose_name='12번 질문의 답')),
                ('q13', models.PositiveIntegerField(verbose_name='13번 질문의 답')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='닉네임')),
                ('age', models.PositiveIntegerField(verbose_name='나이')),
                ('job', models.CharField(max_length=100, verbose_name='직업')),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성'), ('none', '선택하지않음')], max_length=20)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vote.result')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('is_answer', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='vote.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=100, verbose_name='선택지1번')),
                ('choice2', models.CharField(max_length=100, verbose_name='선택지2번')),
                ('choice3', models.CharField(max_length=100, verbose_name='선택지3번')),
                ('choice4', models.CharField(max_length=100, null=True, verbose_name='선택지4번')),
                ('choice5', models.CharField(max_length=100, null=True, verbose_name='선택지5번')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='vote.question', verbose_name='질문')),
            ],
        ),
    ]
