# Generated by Django 3.1.7 on 2021-03-06 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='candidate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='후보자이름'),
        ),
        migrations.AlterField(
            model_name='result',
            name='q1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='1번 질문의 답'),
        ),
        migrations.AlterField(
            model_name='result',
            name='q10',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='10번 질문의 답'),
        ),
        migrations.AlterField(
            model_name='result',
            name='q11',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='11번 질문의 답'),
        ),
        migrations.AlterField(
            model_name='result',
            name='q12',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='12번 질문의 답'),
        ),
        migrations.AlterField(
            model_name='result',
            name='q13',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='13번 질문의 답'),
        ),
        migrations.AlterField(
            model_name='result',
            name='q2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='2번 질문의 답'),
        ),
        migrations.AlterField(
            model_name='result',
            name='q3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='3번 질문의 답'),
        ),
        migrations.AlterField(
            model_name='result',
            name='q4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='4번 질문의 답'),
        ),
        migrations.AlterField(
            model_name='result',
            name='q5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='5번 질문의 답'),
        ),
        migrations.AlterField(
            model_name='result',
            name='q6',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='6번 질문의 답'),
        ),
        migrations.AlterField(
            model_name='result',
            name='q7',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='7번 질문의 답'),
        ),
        migrations.AlterField(
            model_name='result',
            name='q8',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='8번 질문의 답'),
        ),
        migrations.AlterField(
            model_name='result',
            name='q9',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='9번 질문의 답'),
        ),
        migrations.AlterField(
            model_name='user',
            name='result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.result'),
        ),
    ]
