# Generated by Django 3.1.7 on 2021-03-21 09:01

from django.db import migrations, models
import vote.models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[vote.models.is_nickname], verbose_name='닉네임'),
        ),
    ]
